//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod order;
pub mod permission;
pub mod product;
pub mod role;
pub mod role_permission;
pub mod user;
pub mod user_role;
