//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::order::Entity as Order;
pub use super::permission::Entity as Permission;
pub use super::product::Entity as Product;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
